from building import *
Import('rtconfig')

src   = []
cwd   = GetCurrentDir()

CPPPATH = []
LOCAL_CFLAGS = ''

if GetDepend('SPI_NAND_DOSILICON'):
    src += Glob('dosilicon.c')

if GetDepend('SPI_NAND_ETRON'):
    src += Glob('etron.c')

if GetDepend('SPI_NAND_MACRONIX'):
    src += Glob('macronix.c')

if GetDepend('SPI_NAND_WINBOND'):
    src += Glob('winbond.c')

if GetDepend('SPI_NAND_GIGADEVICE'):
    src += Glob('gigadevice.c')

if GetDepend('SPI_NAND_TOSHIBA'):
    src += Glob('toshiba.c')

if GetDepend('SPI_NAND_FORESEE'):
    src += Glob('foresee.c')

if GetDepend('SPI_NAND_XTX'):
    src += Glob('xtx.c')

if GetDepend('SPI_NAND_ZETTA'):
    src += Glob('zetta.c')

if GetDepend('SPI_NAND_MICRON'):
    src += Glob('micron.c')

if GetDepend('SPI_NAND_ZBIT'):
    src += Glob('zbit.c')

if GetDepend('SPI_NAND_ESMT'):
    src += Glob('esmt.c')

if GetDepend('SPI_NAND_UMTEK'):
    src += Glob('umtek.c')

if GetDepend('SPI_NAND_QUANXING'):
    src += Glob('quanxing.c')

if GetDepend('SPI_NAND_XINCUN'):
    src += Glob('xincun.c')

if GetDepend('SPI_NAND_FUDANMICRO'):
    src += Glob('fudanmicro.c')

if GetDepend('SPI_NAND_UNIM'):
    src += ['unim.c']

if GetDepend('LPKG_USING_SPINAND'):
    src += Glob('spinand.c')
    src += Glob('bbt.c')
    src += Glob('spinand_ooblayout.c')
    src += Glob('spinand_bbt.c')
    CPPPATH += [cwd + '/inc']

    if rtconfig.PLATFORM in ['gcc', 'armclang']:
        LOCAL_CFLAGS += ' -std=c99'
    elif rtconfig.PLATFORM in ['armcc']:
        LOCAL_CFLAGS += ' --c99'

# add src and include to group.
group = DefineGroup('spinand', src, depend = ['LPKG_USING_SPINAND'], CPPPATH = CPPPATH, LOCAL_CFLAGS = LOCAL_CFLAGS)

Return('group')


