/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.0
 */

/* lv_conf_custom.h for custom lv_conf.h file
 * example :
 *     #undef LV_USE_LOG
 *     #define LV_USE_LOG 1
 */

#ifndef LV_CONF_CUSTOM_H
#define LV_CONF_CUSTOM_H

/* code  begin */

#undef LV_USE_FREETYPE
#define LV_USE_FREETYPE 0

#undef LV_USE_PERF_MONITOR
#define LV_USE_PERF_MONITOR 1

#undef LV_USE_MEM_MONITOR
#define LV_USE_MEM_MONITOR 0

#undef LV_COLOR_DEPTH
#define LV_COLOR_DEPTH 16

#undef LV_USE_FONT_COMPRESSED
#define LV_USE_FONT_COMPRESSED 0

#undef LV_USE_GIF
#define LV_USE_GIF 0

#undef LV_USE_FS_POSIX
#define LV_USE_FS_POSIX 0

#undef LV_FS_POSIX_LETTER
#undef LV_FS_POSIX_PATH
#undef LV_FS_POSIX_CACHE_SIZE

#if LV_USE_PERF_MONITOR
#undef LV_USE_PERF_MONITOR_POS
#define LV_USE_PERF_MONITOR_POS LV_ALIGN_CENTER
#endif

#undef LV_DRAW_BUF_STRIDE_ALIGN
#define LV_DRAW_BUF_STRIDE_ALIGN 1

#undef LV_DRAW_LAYER_SIMPLE_BUF_SIZE
#define LV_DRAW_LAYER_SIMPLE_BUF_SIZE   (256)

#undef LV_USE_OS
#define LV_USE_OS   LV_OS_NONE

#define  SPI_DEMO_BENCHMARK 0

#if SPI_DEMO_BENCHMARK == 1
#define LV_USE_DEMO_BENCHMARK 1
#undef LV_FONT_MONTSERRAT_24
#define LV_FONT_MONTSERRAT_24 1
#undef LV_USE_DEMO_WIDGETS
#define LV_USE_DEMO_WIDGETS 1
#endif

/* code end */

#endif  /* LV_CONF_CUSTOM_H */
