/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.0
 */

#include "ui_objects.h"
#include "aic_ui.h"


void screen_create(ui_manager_t *ui)
{
    screen_t *scr = screen_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->animImg_1
    scr->animImg_1 = lv_animimg_create(scr->obj);
    static const lv_img_dsc_t *animImg_1_imgs[20] = {
        &r_anim_g1_240x240,
        &r_anim_g2_240x240,
        &r_anim_g3_240x240,
        &r_anim_g4_240x240,
        &r_anim_g5_240x240,
        &r_anim_g6_240x240,
        &r_anim_g7_240x240,
        &r_anim_g8_240x240,
        &r_anim_g9_240x240,
        &r_anim_g10_240x240,
        &r_anim_g11_240x240,
        &r_anim_g12_240x240,
        &r_anim_g13_240x240,
        &r_anim_g14_240x240,
        &r_anim_g15_240x240,
        &r_anim_g16_240x240,
        &r_anim_g17_240x240,
        &r_anim_g18_240x240,
        &r_anim_g19_240x240,
        &r_anim_g20_240x240,
    };

    lv_animimg_set_src(scr->animImg_1, (const void **)animImg_1_imgs, 20);
    lv_animimg_set_duration(scr->animImg_1, 500);
    lv_animimg_set_repeat_count(scr->animImg_1, LV_ANIM_REPEAT_INFINITE);
    lv_animimg_start(scr->animImg_1);
    lv_obj_set_pos(scr->animImg_1, 0, 0);
    lv_obj_set_size(scr->animImg_1, 240, 240);
}


