/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.0
 */

#include "ui_init.h"
#include "aic_ui.h"
#include "custom/custom.h"
#include "lvgl/demos/lv_demos.h"

ui_manager_t ui_manager;

void ui_init(void)
{
#if SPI_DEMO_BENCHMARK
    lv_demo_benchmark();
#else
    // auto delete screen
    ui_manager_init(&ui_manager, true);

    screen_create(&ui_manager);
    lv_scr_load(screen_get(&ui_manager)->obj);

    // custom code
    custom_init();
#endif

}
