/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.0
 */

#ifndef _UI_OBJECTS
#define _UI_OBJECTS

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "lv_conf_custom.h"


typedef struct {
    lv_obj_t *obj;
    lv_obj_t *animImg_1;
} screen_t;


typedef struct {
    bool auto_del;
    screen_t screen;

} ui_manager_t;

static inline void ui_manager_init(ui_manager_t *ui, bool auto_del)
{
    memset(ui, 0 , sizeof(ui_manager_t));
    ui->auto_del = auto_del;
}

static inline screen_t *screen_get(ui_manager_t *ui)
{
    return &ui->screen;
}


void screen_create(ui_manager_t *ui);


LV_IMG_DECLARE(r_anim_g1_240x240)
LV_IMG_DECLARE(r_anim_g2_240x240)
LV_IMG_DECLARE(r_anim_g3_240x240)
LV_IMG_DECLARE(r_anim_g4_240x240)
LV_IMG_DECLARE(r_anim_g5_240x240)
LV_IMG_DECLARE(r_anim_g6_240x240)
LV_IMG_DECLARE(r_anim_g7_240x240)
LV_IMG_DECLARE(r_anim_g8_240x240)
LV_IMG_DECLARE(r_anim_g9_240x240)
LV_IMG_DECLARE(r_anim_g10_240x240)
LV_IMG_DECLARE(r_anim_g11_240x240)
LV_IMG_DECLARE(r_anim_g12_240x240)
LV_IMG_DECLARE(r_anim_g13_240x240)
LV_IMG_DECLARE(r_anim_g14_240x240)
LV_IMG_DECLARE(r_anim_g15_240x240)
LV_IMG_DECLARE(r_anim_g16_240x240)
LV_IMG_DECLARE(r_anim_g17_240x240)
LV_IMG_DECLARE(r_anim_g18_240x240)
LV_IMG_DECLARE(r_anim_g19_240x240)
LV_IMG_DECLARE(r_anim_g20_240x240)

extern ui_manager_t ui_manager;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif // _UI_OBJECTS
