/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.0
 */

#include <stdbool.h>
#include <stdio.h>

#include "lv_aic_player.h"
#include "lvgl.h"

    static void btn_cb(lv_event_t *e){
    lv_obj_t *cont1 = lv_event_get_user_data(e);

    static bool  opaa= false;
    lv_obj_set_style_bg_opa(cont1, opaa?LV_OPA_100:LV_OPA_80, LV_PART_MAIN);
    opaa = !opaa;
    }

/* 初始化视频播放器页面。 */
void ui_init(void)
{
    

    lv_obj_t *cont = lv_obj_create(lv_scr_act());
    lv_obj_set_size(cont, 600, 200);
    lv_obj_set_style_bg_color(cont, lv_color_hex(0x777777), 0);
    lv_obj_set_style_radius(cont, 20, 0);
    lv_obj_set_style_border_width(cont, 0, 0);
    lv_obj_set_style_pad_all(cont, 0, 0);
    lv_obj_align(cont, LV_ALIGN_CENTER, 0, -100);
    lv_obj_set_style_clip_corner(cont, true, 0);

    lv_obj_t *cont1 = lv_obj_create(cont);
    lv_obj_set_size(cont1, 300, 175);
    lv_obj_set_style_bg_color(cont1, lv_color_white(), 0);
    lv_obj_set_style_radius(cont1, 0, 0);
    lv_obj_set_style_border_width(cont1, 0, 0);
    lv_obj_set_style_pad_all(cont1, 0, 0);
    lv_obj_align(cont1, LV_ALIGN_LEFT_MID, 80, 0);

    lv_obj_set_style_bg_opa(cont1, LV_OPA_80, LV_PART_MAIN);

    lv_obj_t *btn = lv_btn_create(lv_scr_act());
    lv_obj_set_size(btn, 300, 100);
    lv_obj_align(btn, LV_ALIGN_CENTER, 0, 100);
    
    lv_obj_add_event_cb(btn, btn_cb, LV_EVENT_SHORT_CLICKED, cont1);

}
