
from building import *
import rtconfig

cwd     = GetCurrentDir()
src     = []
CPPPATH = []
if GetDepend(['RT_USING_FAL']):
    src     = Glob('src/*.c')
    CPPPATH = [cwd + '/inc']

if GetDepend(['FAL_USING_SFUD_PORT']):
    src += Glob('samples/porting/fal_flash_sfud_port.c')

group = DefineGroup('Fal', src, depend = ['RT_USING_FAL'], CPPPATH = CPPPATH)

Return('group')
