/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.1.0
 */

#ifndef CUSTOM_CODE
#define CUSTOM_CODE
#ifdef __cplusplus
extern "C" {
#endif

#include "ui_objects.h"
#include "aic_ui.h"

void custom_init();

#ifdef __cplusplus
}
#endif
#endif /* CUSTOM_CODE */
