/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by UIBuilder
 * UIBuilder version: v2.2.0
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"



void screen_create(ui_manager_t *ui)
{
    screen_t *scr = screen_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_1
    scr->button_1 = lv_btn_create(scr->obj);
    lv_obj_t *button_1_label = lv_label_create(scr->button_1);
    lv_label_set_text(button_1_label, "Button");
    lv_obj_align(button_1_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_1, 6, 8);
    lv_obj_set_size(scr->button_1, 87, 43);

    // Set style of scr->button_1
    lv_obj_set_style_shadow_width(scr->button_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_1, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_2
    scr->button_2 = lv_btn_create(scr->obj);
    lv_obj_t *button_2_label = lv_label_create(scr->button_2);
    lv_label_set_text(button_2_label, "Button");
    lv_obj_align(button_2_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_2, 1348, 8);
    lv_obj_set_size(scr->button_2, 87, 43);

    // Set style of scr->button_2
    lv_obj_set_style_shadow_width(scr->button_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_2, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_3
    scr->button_3 = lv_btn_create(scr->obj);
    lv_obj_t *button_3_label = lv_label_create(scr->button_3);
    lv_label_set_text(button_3_label, "Button");
    lv_obj_align(button_3_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_3, 6, 669);
    lv_obj_set_size(scr->button_3, 87, 43);

    // Set style of scr->button_3
    lv_obj_set_style_shadow_width(scr->button_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_3, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_4
    scr->button_4 = lv_btn_create(scr->obj);
    lv_obj_t *button_4_label = lv_label_create(scr->button_4);
    lv_label_set_text(button_4_label, "Button");
    lv_obj_align(button_4_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_4, 1348, 669);
    lv_obj_set_size(scr->button_4, 87, 43);

    // Set style of scr->button_4
    lv_obj_set_style_shadow_width(scr->button_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_4, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_5
    scr->button_5 = lv_btn_create(scr->obj);
    lv_obj_t *button_5_label = lv_label_create(scr->button_5);
    lv_label_set_text(button_5_label, "Button");
    lv_obj_align(button_5_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_5, 676, 338);
    lv_obj_set_size(scr->button_5, 87, 43);

    // Set style of scr->button_5
    lv_obj_set_style_shadow_width(scr->button_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_5, fs_montserratmedium_16, LV_PART_MAIN | LV_STATE_DEFAULT);


}


