Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
CPPPATH = []
src = []
if GetDepend('AIC_CANFD_DRV_TEST') and GetDepend('RT_USING_FINSH'):
    src += Glob('*.c')

group = DefineGroup('test-canfd', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
